### ISSUE TITLE
CMD key

### ISSUE THREAD

**Issue by H-Max** [nleclerc/fmbkl4w#1]
Is there any plan to support the CMD key ?

I'm using Microsoft Remote Desktop on a my Mac and when I want to copy from the remote session to my local machine, I have to switch from CTRL to CMD, and CMD to CTRL.

This would be a perfect addition to this key mapping, IMHO...

**Comment by nleclerc** [comment]
I wouldn't be very confortable not matching the actual keyboard layout but you can do as i do and use [sharpkeys](https://sharpkeys.codeplex.com/).

Hope that helps.

**Comment by H-Max** [comment]
Thanks, I'm gonna check this out.
